org: orgDemo # (optional) serverless dashboard org. default is the first org you created during signup.
app: appDemo # (optional) serverless dashboard app. default is the same as the name property.
stage: dev # (optional) serverless dashboard stage. default is dev.
component: express # (required) 组件名是固定的，并且会寻找目录下的sls.js（名字固定）
name: yxdExpress # (required) name of your express component instance.

inputs:
  src: ./src
  region: ap-beijing
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
  # 可以配置ignore：具体查看tencent-egg的更多配置
